---

server_root_dir: "/{{ server_root_name }}"

celery_user: "{{ env_user }}"
celery_group: "{{ server_root_name }}"

celery_application_name: celery
celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"
celery_template_file: "{{ celery_application_name }}_start.j2"

celery_log_dir: "{{ virtualenv_path }}/logs"
celery_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}.log"
