---

- name: Create {{ application_name }} virtual machine in vagrant
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: vagrant
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml
  roles:
    - base
    - db
    - rabbitmq
    - web
    - celery
