---

- name: Provision {{ application_name }} web server in {{ env }}
  hosts: web
  become: yes
  become_method: sudo
  become_user: root
  remote_user: root
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
  roles:
    - base
    - web
