---

- name: restart application
  command: supervisorctl restart {{ application_name }}

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded
